build:
    environment:
        php:
            version: 7.0.7       # Common versions: 5.4, 5.5, 5.6, 7.0, 7.1, or hhvm
    tests:
        override:
            -
                command: phpunit --coverage-clover=my-coverage-file --configuration phpunit.xml
                coverage:
                    file: my-coverage-file
                    format: php-clover
checks:
    php: true